AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create a CloudFront distribution for an S3 bucket static website.'

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket to be used as the origin for the CloudFront distribution

Resources:
  
  S3BucketWebsitePolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BucketName
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOAI}"
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${BucketName}/*"


  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub Access Identity for ${AWS::StackName}

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub CloudFront Distribution for the S3 website ${BucketName}
        Enabled: true
        Origins:
          - DomainName: !Sub ${BucketName}.s3.amazonaws.com
            Id: S3-Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOAI}
        DefaultCacheBehavior:
          TargetOriginId: S3-Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - HEAD
            - GET
          CachedMethods:
            - HEAD
            - GET
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
        DefaultRootObject: index.html
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:
  DistributionId:
    Description: The ID of the CloudFront Distribution
    Value: !Ref CloudFrontDistribution

  DistributionDomainName:
    Description: The domain name of the CloudFront Distribution
    Value: !GetAtt CloudFrontDistribution.DomainName
