AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Sample Template: S3 Bucket for Static Website Hosting.'

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket

Resources:

  S3BucketForWebsite:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3BucketForWebsite
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${S3BucketForWebsite}/*'

Outputs:
  WebsiteURL:
    Value: !GetAtt [S3BucketForWebsite, WebsiteURL]
    Description: 'URL of the website hosted on this S3 bucket'
  S3BucketSecureURL:
    Value: !Sub 'https://${S3BucketForWebsite}.s3.amazonaws.com'
    Description: 'The HTTPS URL of the S3 bucket to access the website.'
